version: '3.8'

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    # command: npm run dev -- --host
    volumes:
      - ./:/app
      - ./node_modules
    ports:
      - 8080:8080
    stdin_open: true