name: Build and Push Docker Image
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}/chat-front # ${{}} 은 변수. 본인 user-name
  VERSION: ${{ github.sha }} 
  NAME: dohee_cicd

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache docker layers
      uses: actions/cache@v2
      with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }} # runner 설정에서 읽어들일거에요.
          restore-keys: |
            ${{ runner.os }}-buildx-
    - name: Login to ghcr
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_DH }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ env.REGISTRY}}/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

  # deploy:
  #   needs: build-and-push-image
  #   name: Deploy
  #   runs-on: self-hosted 
  #   steps:
  #     - name: Login to ghcr
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.DOCKER_DH }}
  #     - name: Docker run
  #       run: |
  #         docker ps -q --filter "name=dh_container" | grep -q . && docker stop dh_container && docker rm -fv dh_container
  #         docker run -itd -p 8080:8080 --name dh_container --restart always ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}